# Generated by Django 4.1.2 on 2022-10-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="descripction",
            new_name="description",
        ),
    ]
